const lib = require('lib')({token: process.env.STDLIB_SECRET_TOKEN});
let messagePrompts = [
  'If money were no object, what would you do?',
  'If you found out you were going to die tomorrow, what would you do today?',
  'What is the most unexpected piece of advice you ever received?',
  'If you could ask your future self one question, what would it be?',
  'If you could tell your past self one thing, what would it be?',
  'If you could ask one question to an all-knowing being, what would it be?',
  'What do you think happens after death?',
  'What is the most profound experience you have ever had with a stranger?',
  'What is the biggest risk you have ever taken?',
  'What is a moment you realized you were wrong and what was the cause of this epiphany?',
  'What event changed your perspective on life?',
  'What is the most unexpected turn your life took?',
  'If you could change one historic event, which one would it be?',
  'What was the most humbling moment in your life so far?',
  'How do you make the world a better place?',
  'What do you consider to be your personal calling?',
  'If you weren’t afraid of failure, what would you do differently?',
  'What is your most treasured memory?',
  'What personal quality do you most want to improve?',
  'What is something that wish someone would say to you?',
  'What would your younger self think of who you are today?',
  'What do you want people to say about you when you are not around?',
  'What part of your identity do you believe will never change?',
  'What is your earliest memory?',
  'If you could choose a brand new name for yourself, what would it be?',
  'If you could learn one skill instantly, what would it be?',
  'If you were to write a book, what would it be about?',
  'If you suddenly had powers of invisibility, what would you use them for?',
  'What is the best business idea you have ever had?',
  'If you could un-invent one thing, what would it be?',
  'If you had to live as an animal for one year, which one would you choose and why?',
  'What is the most unbelievable-yet-true excuse you have ever had for being late?',
  'What is your favorite word to say out loud?',
  'Which number to you like the most?',
  'What is the most thoughtful present you have ever received?',
  'What is the oddest way you ever accidentally hurt yourself?',
  'What is a song that immediately takes you back to a particular moment in your life?',
  'What was something that wound up being totally different than you imagined it to be?',
  'Do you think you could live in outer space for a year?',
  'What kind of baby animal would you most love to be surrounded by?',
  'If you could have any animal as a pet, which one would you choose?',
  'What is the stupidest thing you ever did on a dare?',
  'What is your idea of the perfect day?',
  'What are your must-have qualities in a best friend?',
  'What is the most embarrassing thing your parents have ever done?',
  'When was the last time you laughed so hard that you cried?',
  'What would your dream house look like?',
  'What is the meanest thing you ever did to a sibling or that a sibling did to you?',
  'What was your best birthday ever?',
  'Which three words describe you the most?',
  'What is the best meal you have ever eaten?',
  'What is something that never fails to make you laugh?',
  'Have you ever lost a bet? What was it? What were the consequences?',
  'If you could watch any movie again for the first time, what would you watch?',
  'What country would you most like to visit?',
  'What is the most random thing you have cried about?',
  'What word do you use most often?',
  'What is the nicest compliment you ever received?',
  'What is your favorite kind of weather?',
  'If you could dis-invent one thing, what would it be?',
  'If you were given a chance to change your career, what could be your dream job?',
  'If you had to listen to one song for the rest of your life, what would it be?',
  'What is your favorite fast food to eat?',
  `What's the worst movie you've ever seen?`,
  `What's one thing you'd like to do better at in life?`,
  `What's the worst thing you've ever done?`,
  `If you had one wish, what would it be?`,
  `What movie do you wish you could have made?`,
  `What's the funniest joke you've ever heard?`,
  `If you could be famous, what would you want to be famous for?`,
  `Which country would you own if you could own any country in the world?`,
  `Who was your favorite character on TV?`,
  `If you could time travel, when would you go?`,
  `What is the best piece of advice you’ve received?`,
  `What’s the scariest dream you’ve ever had?`,
  `If you could visit one planet, which would it be?`,
  `What super power do you wish you had?`,
  `What makes you happiest?`,
  `What country do you most want to travel to?`,
  `Which foreign language would you like to learn?`,
  `What’s your favorite color?`,
  `How would you spend 100 million dollars?`,
  `If you won the lottery tomorrow, what would be your very first expense?`,
  `What’s the biggest misstep you’ve ever taken?`,
  `What skill do you wish you had?`,
  `What job could you never imagine doing?`,
  `What’s your greatest fear while swimming in the ocean?`,
  `What’s your greatest fear while swimming in the ocean?`,
  `What’s the best thing you’ve ever eaten?`,
  `Which discord server is the greatest?`,
  `If you had exactly one wish to make that would come true ten years from now, what would it be?`,
  `What do you do when you can’t fall asleep?`,
  `What’s something you always wanted to do as a child but never got to do it?`,
  `What is the strangest thing you’ve ever eaten?`,
  `Who do you like to annoy the most?`,
  `Who do you pretend to like, but actually don't?`,
  `What's the most embarrassing nickname you've ever had?`,
  `Do you know how to cook?`,
  `Are you scared of dying?`,
  `What was the longest time you've gone without sleeping?`,
  `What is your favourite game to play?`,
  `Do you have a pet? If yes what's their name?`,
  `If you could rid the world of one disease what would it be?`,
  `What’s the worst thing you ever did as a child and what was your punishment?`,
  `Describe the worst haircut you’ve ever had!`,
  `What is the funniest movie you have ever seen?`,
  `What country would you never want to visit?`,
  `What kind of phone was your first cell phone?`,
  `On a scale from 1-10 what’s the highest level of pain you’ve ever been in?`,
  `If you could start a collection of one kind of item, what would it be?`,
  `Who is the most famous person you have ever met?`,
  `You’re in prison with a life sentence, what was your crime?`,
  `What two languages would you like to be fluent in?`,
  `What is your favorite sport in the Winter Olympics?`,
  `If it were possible, would you live on the moon?`,
  `If you could break any world record which one would it be?`,
  `What’s the weirdest dream you’ve ever had?`,
  `If you could master one musical instrument, what would it be?`,
  `Have you ever been drunk in public?`,
  `If money were no object, where in the world would you choose to live?`,
  `Have you ever saved someone’s life?`,
  `Has anyone ever saved your life?`,
  `Would you like to live to be 200 years old?`,
  `Would you become a professional bank robber if you knew you would never get caught?`,
];

let messageChoice = Math.floor(Math.random() * messagePrompts.length);
let message = messagePrompts[messageChoice];
await lib.discord.channels['@0.3.2'].messages.create({
  channel_id: `${context.params.event.channel_id}`,
  content: '',
  tts: false,
  embeds: [
    {
      type: 'rich',
      title: ``,
      description: `${message}`,
      color: 0x00ffff,
      image: {
        url: `https://media.discordapp.net/attachments/901557716642828338/1051030935564472340/vragenkinderen.jpg`,
        height: 0,
        width: 0,
      },
    },
  ],
});
